name: newsletter-api

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true" # for dev only (TODO: secure auth for prod)
      - "--api.dashboard=true"
      - "--providers.file.filename=/etc/traefik/dynamic.dev.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.dev.yml:/etc/traefik/dynamic.dev.yml
    networks:
      - newsletter-net

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    networks:
      - newsletter-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  test_a:
    build:
      context: .
      dockerfile: services/test-a/Dockerfile
      target: dev
    container_name: test_a
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./services/test-a:/app/services/test-a
      - ./libs:/app/libs
    networks:
      - newsletter-net
    command: ["air", "-c", "services/test-a/.air.toml"]
    depends_on:
      - db
      - traefik

networks:
  newsletter-net:
    driver: bridge
