name: newsletter-api

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true" # for dev only (TODO: secure auth for prod)
      - "--api.dashboard=true"
      - "--providers.file.filename=/etc/traefik/dynamic.prod.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.prod.yml:/etc/traefik/dynamic.prod.yml
    networks:
      - newsletter-net

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    networks:
      - newsletter-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  test_a:
    build:
      context: .
      dockerfile: services/test-a/Dockerfile
    container_name: test_a
    networks:
      - newsletter-net

networks:
  newsletter-net:
    driver: bridge
