http:
  routers:
    test-a:
      rule: "PathPrefix(`/api/test`)"
      service: test_a-service
      entryPoints:
        - web
      middlewares:
        - strip-api

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"

  services:
    test_a-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8081"
